### ISSUE TITLE
builtin libraries issue

### ISSUE THREAD

**Issue by Faizanf33** [RafayGhafoor/PTCL-Router-API#1]
1. Error in import configobj
fixed using command "pip install configobj"
2. Error in import tabulate
fixed using command "pip install tabulate"
3. AttributeError: 'Router' object has no attribute 'get_stationinfo', comes with the selection of -a

**Comment by RafayGhafoor** [comment]
I apologize for the problem in the build, and I am aware of the issues you raised. I will fix them soon :)
